### ISSUE TITLE
Add a parameter named "enabled" in AddRabbitConsumer function.

### ISSUE THREAD

**Issue by velviagris** [cgcel/NanoRabbit#11]
Hi Levan @Revazashvili , I have an idea about adding a parameter named "enabled" in AddRabbitConsumer function, defaults to true, this parameter makes debugging more convenience. If I'm using appsettings.json in my project, I can simply set the "enabled" to true/false to enble/disable the consumer/producer, for example:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "FooConfiguration": {
    "HostName": "localhost",
    "Port": 5672,
    "UserName": "admin",
    "Password": "admin",
    "VirtualHost": "/",

    "Producers": [
      {
        "ProducerName": "FooProducer",
        "ExchangeName": "amq.topic",
        "RoutingKey": "foo.key",
        "Type": "topic"
      },
      {
        "ProducerName": "BarProducer",
        "ExchangeName": "amq.direct",
        "RoutingKey": "bar.key",
        "Type": "direct"
      }
    ],
    "Consumers": [
      {
        "ConsumerName": "FooConsumer",
        "QueueName": "foo-queue",
        "Enabled":  false
      },
      {
        "ConsumerName": "BarConsumer",
        "QueueName": "bar-queue"
      }
    ]
  }
}
```

or:

```csharp
builder.Services.AddRabbitHelper(builder =>
{
    builder.SetHostName("localhost")
        .SetPort(5672)
        .SetVirtualHost("/")
        .SetUserName("admin")
        .SetPassword("admin")
        .AddProducerOption(producer =>
        {
            producer.ProducerName = "FooProducer";
            producer.ExchangeName = "amq.topic";
            producer.RoutingKey = "foo.key";
            producer.Type = ExchangeType.Topic;
        })
        .AddConsumerOption(consumer =>
        {
            consumer.ConsumerName = "FooConsumer";
            consumer.QueueName = "foo-queue";
        })
        .AddConsumerOption(consumer =>
        {
            consumer.ConsumerName = "BarConsumer";
            consumer.QueueName = "bar-queue";
        });
})
.AddRabbitConsumer<FooQueueHandler>("FooConsumer", consumers: 3, enabled: true)
.AddRabbitConsumer<BarQueueHandler>("BarConsumer", consumers: 2, enabled: false);
```

I'd like to know your opinion on the necessity of adding this feature.

**Comment by Revazashvili** [comment]
Hi, i don't think you need this. I have never needed to turn on and off consumer or producer in this way while using some package. if you need it for testing purpose you can just comment you code, test and uncomment it.

Think from client side, you call ```AddConsumer``` method which takes ```enabled``` parameter, what does it do? if client doesn't want to run consumer, simply won't call that method. it complicates things. in both way you have to stop application and run again, it's same if you change false to true, or comment some line.

**Comment by Revazashvili** [comment]
What was problem while debugging code, that made you think to add parameter like this? maybe we can solve it another way

**Comment by cgcel** [comment]
Yes you are right, it's unnecessary to add this param, so I will close this issue.

**Comment by velviagris** [comment]
> What was problem while debugging code, that made you think to add parameter like this? maybe we can solve it another way

Yes you are right, it's unnecessary to add this param, so I will close this issue.
