### ISSUE TITLE
EditorConfig support

### ISSUE THREAD

**Issue by Revazashvili** [cgcel/NanoRabbit#15]
Have you thought about adding .editorconfig file to project? for me, this projects has lack of standard how code should be written. editor config would help to form code structure.

**Comment by velviagris** [comment]
Hi, I seldom used .editorconfig in my project because I mantained them alone most of times🤣, but it is a great chance to start using .editorconfig, could you add one to NanoRabbit? Thx :)

**Comment by Revazashvili** [comment]
Sure, I'll start working on it, I'll need to identify coding standards that's used in project and then we'll add it step by step

**Comment by velviagris** [comment]
Hi, I just added .editorconfig for NanoRabbit, plz check if any configs are missed.

**Comment by Revazashvili** [comment]
it looks good to me, couple of configs can be changed but I will take a good look during coding.
