### ISSUE TITLE
Questions about the parameter "loggerFactory" of AddRabbitHelper

### ISSUE THREAD

**Issue by velviagris** [cgcel/NanoRabbit#17]
@Revazashvili Hi Levan,

I have a question about the parameter "loggerFactory" of AddRabbitHelper, at this version, `AddRabbitHelper()` is defined like the code below:

```csharp
public static IServiceCollection AddRabbitHelper(this IServiceCollection services, Action<RabbitConfigurationBuilder> builder, Func<IServiceCollection, ILogger>? loggerFactory = null)
{
    var rabbitConfigBuilder = new RabbitConfigurationBuilder();
    builder.Invoke(rabbitConfigBuilder);
    var rabbitConfig = rabbitConfigBuilder.Build();

    services.AddSingleton<IRabbitHelper>(_ => new RabbitHelper(rabbitConfig, GetLogger(services, loggerFactory)));
    return services;
}
```

The type of loggerFactory is `Func<IServiceCollection, ILogger>?`, but when I am using this function in my project, I felt a little wired, usually, we inject a ILogger at `Program.cs`, not create a new ILogger and pass it into `AddRabbitHelper()`, how about change the type of loggerFactory to `Func<IServiceCollection, ILogger>?`? The code might like this:

```csharp
public static IServiceCollection AddRabbitHelper(this IServiceCollection services, Action<RabbitConfigurationBuilder> builder, Func<IServiceProvider, ILogger>? loggerFactory = null)
{
    var rabbitConfigBuilder = new RabbitConfigurationBuilder();
    builder.Invoke(rabbitConfigBuilder);
    var rabbitConfig = rabbitConfigBuilder.Build();

    services.AddSingleton<IRabbitHelper>(provider => new RabbitHelper(rabbitConfig, GetLogger(provider, loggerFactory)));
    return services;
}

private static ILogger GetLogger(IServiceProvider provider, Func<IServiceProvider, ILogger>? loggerFactory)
{
    return loggerFactory != null ? loggerFactory(provider) : provider.GetRequiredService<ILogger>();
}
```

Now we can get ILogger from serviceProvider without creating it again while calling `AddRabbitHelper()`.

**Comment by Revazashvili** [comment]
Hi,

if you want to change last parameter type of AddRabbitHelper, from ```Func<IServiceCollection, ILogger>?``` to ```Func< IServiceProvider, ILogger>?``` I'm okay with that, but in this method that you provided:

```
private static ILogger GetLogger(IServiceProvider provider, Func<IServiceProvider, ILogger>? loggerFactory)
{
    return loggerFactory != null ? loggerFactory(provider) : provider.GetRequiredService<ILogger>();
}
```
is slight problem, how do you know that ```provider.GetRequiredService``` method call will return service and not throw exception, how do you that there is logger injected in DI Container?

**Comment by Revazashvili** [comment]
in my ```GetLogger``` method implementation

```
private static ILogger GetLogger(IServiceCollection services, Func<IServiceCollection, ILogger>? loggerFactory = null)
{
    var logger = loggerFactory is null ? NullLogger : loggerFactory(services);

    return logger;
}
```

reason why I return ```NullLogger``` is that you client of library does not want to provide custom logger factory means that there is no need for logging, but for classes that inject ```ILogger``` where must be some implementation, ```NullLogger``` is perfect one, you don't have to check null variable all the time and also logs are emited as library client wanted.

**Comment by velviagris** [comment]
@Revazashvili Okey, I decided not to change it. NullLogger is a good solution when no ILogger injected.
